plotClusterWaveforms <- function( host, user, password, dbname, table, seizureUsed, clusterid, ylim=c(-250,250) ) {
  # After timeVoltage2tibble.R
  # 'output' is generated by 'parallelWindowNPO' and is a list of vectors.
  #
  # Get the 'output' variable by running:
  #   load(file='output.RData')
  library( ggplot2 )
  library( reshape2 )
  library( plyr )
  library( tidyverse )
  
  conn <- topconnect::db( dbname=dbname, host=host, db_user=user, password=password )
  query <- paste0( 'select time,waveform from ', table, ' where seizureUsed=', seizureUsed,' and clusterid=',clusterid,';')
  rs <- DBI::dbGetQuery(conn,query)
  wv <- sapply( 1:nrow(rs), function(x) as.numeric( unlist( stringr::str_split(rs$waveform[[x]],',') ) ), simplify=TRUE )
  DBI::dbDisconnect(conn)
  
  mn <- apply(wv,1,mean)
  sv <- apply(wv,1,sd)
  ymax <- mn + sv
  ymin <- mn - sv
  df <- data.frame()
  N <- ncol(wv)
  for ( idx in seq(1,N) ) {
    df <- rbind( df, data.frame( g=rep(idx,41), x=seq(1,41), y=wv[,idx], lower=ymin, upper=ymax ) )
  }

  #plot
  alpha <- 100/N
  p <- df %>% ggplot( aes(x=x, y=y, group=g)) + geom_line(alpha=alpha) + ylim(ylim) + geom_errorbar(color="white",aes(ymin=lower,ymax=upper)) + labs(title = clusterid)
}

